import { ScrollView, StyleSheet, Text, View } from 'react-native'
import React from 'react'

const PrivacyAndPolicy = () => {
  return (

    <ScrollView style={{ flex: 1, }}>
      <View style={styles.header}>

        <Text style={{ flex: 1, lineHeight: 60, textAlign: 'center', fontSize: 20, color: 'black', }}>Privacy And Policy</Text>


      </View>

      <View style={{ padding: 20 }} >



        <Text style={{ textAlign: 'justify', fontSize: 18 }}>Privacy Policy

          {'\n'}
          Last updated: April 15, 2024

          {'\n'}{'\n'}

          This Privacy Policy describes Our policies and procedures on the collection,
          use and disclosure of Your information when You use the Service and tells You
          about Your privacy rights and how the law protects You.

          We use Your Personal data to provide and improve the Service. By using the
          Service, You agree to the collection and use of information in accordance with
          this Privacy Policy.
          {'\n'}{'\n'}

          Interpretation and Definitions
          {'\n'}{'\n'}


          {'\n'}
          Interpretation
          {'\n'}
          {'\n'}

          The words of which the initial letter is capitalized have meanings defined
          under the following conditions. The following definitions shall have the same
          meaning regardless of whether they appear in singular or in plural.
          {'\n'}{'\n'}

          Definitions
          {'\n'}{'\n'}

          For the purposes of this Privacy Policy:
          {'\n'}
          {'\n'}


          * Account means a unique account created for You to access our Service or
          parts of our Service.
          {'\n'}
          {'\n'}


          * Affiliate means an entity that controls, is controlled by or is under
          common control with a party, where "control" means ownership of 50% or
          more of the shares, equity interest or other securities entitled to vote
          for election of directors or other managing authority.
          {'\n'}{'\n'}


          * Application refers to EasyShop, the software program provided by the
          Company.{'\n'}{'\n'}

          * Company (referred to as either "the Company", "We", "Us" or "Our" in this
          Agreement) refers to ECommerce , Surat.{'\n'}{'\n'}

          * Country refers to: Gujarat, India{'\n'}{'\n'}

          * Device means any device that can access the Service such as a computer, a
          cellphone or a digital tablet.{'\n'}{'\n'}

          * Personal Data is any information that relates to an identified or
          identifiable individual.{'\n'}{'\n'}

          * Service refers to the Application.{'\n'}{'\n'}

          * Usage Data refers to data collected automatically, either generated by the
          use of the Service or from the Service infrastructure itself (for example,
          the duration of a page visit).

          * You means the individual accessing or using the Service, or the company,
          or other legal entity on behalf of which such individual is accessing or
          using the Service, as applicable.

          {'\n'}{'\n'}

          Personal Data
          {'\n'}{'\n'}

          While using Our Service, We may ask You to provide Us with certain personally
          identifiable information that can be used to contact or identify You.
          Personally identifiable information may include, but is not limited to:{'\n'}{'\n'}

          * Email address{'\n'}{'\n'}

          * Phone number{'\n'}{'\n'}

          * Usage Data{'\n'}{'\n'}


          Changes to this Privacy Policy {'\n'}{'\n'}


          We may update Our Privacy Policy from time to time. We will notify You of any
          changes by posting the new Privacy Policy on this page.{'\n'}{'\n'}

          We will let You know via email and/or a prominent notice on Our Service, prior
          to the change becoming effective and update the "Last updated" date at the top
          of this Privacy Policy.{'\n'}{'\n'}

          You are advised to review this Privacy Policy periodically for any changes.
          Changes to this Privacy Policy are effective when they are posted on this
          page.{'\n'}{'\n'}

          Contact Us{'\n'}{'\n'}


          If you have any questions about this Privacy Policy, You can contact us:{'\n'}{'\n'}

          * By email: easyShop@gmail.com{'\n'}{'\n'}

        </Text>
      </View>

    </ScrollView>
  )
}

export default PrivacyAndPolicy

const styles = StyleSheet.create({

  screen: {
    flex: 1,
    marginHorizontal: 16
  },


  header: {
    height: 60,
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: 'white',
    alignItems: 'center',
  },
})